CREATE TABLE PROYECTO (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NOMBRE VARCHAR(100) NOT NULL,
    FECHA_CREACION DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE ARCHIVO (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    NOMBRE_ARCHIVO VARCHAR(100),
    FECHA_CREACION DATE DEFAULT CURRENT_DATE NOT NULL,
    IDPROYECTO INTEGER NOT NULL 
);

CREATE TABLE PALABRACLAVE (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    PALABRA VARCHAR(100),
    TIPO_PALABRA VARCHAR(100),
    PALABRACS VARCHAR(100)
);

CREATE TABLE GRAMATICA (
    ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    GRAMATICA_SENTENCIA VARCHAR(200),
    TIPO_GRAMATICA VARCHAR(100)
);



